
language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - npm -g install typescript@3.5.2

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - cd udagram-feed-api && npm run build && npm run build-image && cd ..
  - cd udagram-users-api && npm run build && npm run build-image && cd ..
  - cd udagram-reverseproxy && sh build.sh && cd ..
  - cd udagram-frontend && npm run build && npm run build-image && cd ..

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - cd udagram-feed-api && npm run push-image && cd ..
  - cd udagram-users-api && npm run push-image && cd ..
  - cd udagram-reverseproxy && sh push.sh && cd ..
  - cd udagram-frontend && npm run push-image && cd ..