apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-api
  labels:
    app: udagram-feed-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-feed-api
  template:
    metadata:
      labels:
        app: udagram-feed-api
    spec:
      containers:
      - name: feed-api
        image: diogosilverio/udagram-feed-api
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "270m"    
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        volumeMounts:
        - name: aws-credentials
          mountPath: /root/.aws
          readOnly: true
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: udagram-secrets
              key: POSTGRES_USERNAME      
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: udagram-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: udagram-envs
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: udagram-envs
              key: POSTGRES_HOST
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: udagram-envs
              key: AWS_REGION
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: udagram-envs
              key: AWS_BUCKET
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: udagram-envs
              key: AWS_PROFILE
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: udagram-envs
              key: JWT_SECRET   
      volumes:
      - name: aws-credentials
        secret:
          secretName: aws-secrets
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always