apiVersion: v1
kind: Service
metadata:
  name: udagram-loadbalancer
spec:
  type: LoadBalancer
  selector:
    service: udagram-reverseproxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080