apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  labels:
    app: udagram-users-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-users-api
  template:
    metadata:
      labels:
        app: udagram-users-api
    spec:
      containers:
      - name: users-api
        image: diogosilverio/udagram-users-api
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "270m"    
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3   
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
