apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-frontend
  name: udagram-frontend-svc
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 8080
  selector:
    service: udagram-frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
