apiVersion: v1
kind: Service
metadata:
  name: udagram-feed-api-svc
  labels:
    app: udagram-feed-api
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: udagram-feed-api
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
